language: python
os: linux
dist: xenial
python:
  - "3.8"
before_install:
  - pip install poetry
  - pip install codecov
  - pip install invoke
install:
  - poetry install
script:
  - invoke test
after_success:
  - codecov
before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
deploy:
  provider: script
  script: invoke deploy
  on:
    branch: master